# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Jimmy Ma

build:
	swift build

run:
	swift run

test:
	swift test

test-integration:
	swift test --filter "TiledIntegrationTests"

test-unit:
	swift test --filter "TiledTests"
